from enum import Enum

GOOGLE_MAPS_API_KEY = "AIzaSyAVB3MJYYKpCHwbs65IwWt73SOqKH9R4w4"

STATUS_PENDING = "Pending"
STATUS_ACTIVE = "Active"
STATUS_CLOSED = "Closed"

TABLE_COLUMN_COMPANY = 0
TABLE_COLUMN_JOB_TITLE = 1
TABLE_COLUMN_DATE_APPLIED = 2
TABLE_COLUMN_STATUS = 3

class FilterMode(Enum):
    ALL = "all"
    ACTIVE = "active"
    CLOSED = "closed"