# Form implementation generated from reading ui file 'UI/edit_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_editDetailsPopup(object):
    def setupUi(self, editDetailsPopup):
        editDetailsPopup.setObjectName("editDetailsPopup")
        editDetailsPopup.resize(302, 176)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(editDetailsPopup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.editDetailsForm = QtWidgets.QFormLayout()
        self.editDetailsForm.setVerticalSpacing(12)
        self.editDetailsForm.setObjectName("editDetailsForm")
        self.companyLabel = QtWidgets.QLabel(parent=editDetailsPopup)
        self.companyLabel.setObjectName("companyLabel")
        self.editDetailsForm.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.companyLabel)
        self.companyLineEdit = QtWidgets.QLineEdit(parent=editDetailsPopup)
        self.companyLineEdit.setObjectName("companyLineEdit")
        self.editDetailsForm.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.companyLineEdit)
        self.jobTitleLabel = QtWidgets.QLabel(parent=editDetailsPopup)
        self.jobTitleLabel.setObjectName("jobTitleLabel")
        self.editDetailsForm.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.jobTitleLabel)
        self.jobTitleLineEdit = QtWidgets.QLineEdit(parent=editDetailsPopup)
        self.jobTitleLineEdit.setObjectName("jobTitleLineEdit")
        self.editDetailsForm.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.jobTitleLineEdit)
        self.applyDateLabel = QtWidgets.QLabel(parent=editDetailsPopup)
        self.applyDateLabel.setObjectName("applyDateLabel")
        self.editDetailsForm.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.applyDateLabel)
        self.applyDateDateEdit = QtWidgets.QDateEdit(parent=editDetailsPopup)
        self.applyDateDateEdit.setObjectName("applyDateDateEdit")
        self.editDetailsForm.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.applyDateDateEdit)
        self.locationLabel = QtWidgets.QLabel(parent=editDetailsPopup)
        self.locationLabel.setObjectName("locationLabel")
        self.editDetailsForm.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.locationLabel)
        self.locationLineEdit = QtWidgets.QLineEdit(parent=editDetailsPopup)
        self.locationLineEdit.setObjectName("locationLineEdit")
        self.editDetailsForm.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.locationLineEdit)
        self.verticalLayout_2.addLayout(self.editDetailsForm)
        self.editDetailsButtons = QtWidgets.QHBoxLayout()
        self.editDetailsButtons.setContentsMargins(64, -1, 64, -1)
        self.editDetailsButtons.setObjectName("editDetailsButtons")
        self.cancelButton = QtWidgets.QPushButton(parent=editDetailsPopup)
        self.cancelButton.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.cancelButton.setObjectName("cancelButton")
        self.editDetailsButtons.addWidget(self.cancelButton, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.saveButton = QtWidgets.QPushButton(parent=editDetailsPopup)
        self.saveButton.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.saveButton.setObjectName("saveButton")
        self.editDetailsButtons.addWidget(self.saveButton, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_2.addLayout(self.editDetailsButtons)

        self.retranslateUi(editDetailsPopup)
        QtCore.QMetaObject.connectSlotsByName(editDetailsPopup)

    def retranslateUi(self, editDetailsPopup):
        _translate = QtCore.QCoreApplication.translate
        editDetailsPopup.setWindowTitle(_translate("editDetailsPopup", "Edit Details"))
        self.companyLabel.setText(_translate("editDetailsPopup", "Company"))
        self.jobTitleLabel.setText(_translate("editDetailsPopup", "Job Title"))
        self.applyDateLabel.setText(_translate("editDetailsPopup", "Apply Date"))
        self.applyDateDateEdit.setDisplayFormat(_translate("editDetailsPopup", "dd/MM/yyyy"))
        self.locationLabel.setText(_translate("editDetailsPopup", "Location"))
        self.cancelButton.setText(_translate("editDetailsPopup", "Cancel"))
        self.saveButton.setText(_translate("editDetailsPopup", "Save"))
