# Form implementation generated from reading ui file 'UI/event_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_new_event_dialog(object):
    def setupUi(self, new_event_dialog):
        new_event_dialog.setObjectName("new_event_dialog")
        new_event_dialog.resize(236, 181)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(new_event_dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.typeLabel = QtWidgets.QLabel(parent=new_event_dialog)
        self.typeLabel.setObjectName("typeLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.typeLabel)
        self.typeComboBox = QtWidgets.QComboBox(parent=new_event_dialog)
        self.typeComboBox.setObjectName("typeComboBox")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.typeComboBox)
        self.dateLabel = QtWidgets.QLabel(parent=new_event_dialog)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dateLabel)
        self.dateDateEdit = QtWidgets.QDateEdit(parent=new_event_dialog)
        self.dateDateEdit.setObjectName("dateDateEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateDateEdit)
        self.noteLabel = QtWidgets.QLabel(parent=new_event_dialog)
        self.noteLabel.setObjectName("noteLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.noteLabel)
        self.noteTextEdit = QtWidgets.QTextEdit(parent=new_event_dialog)
        self.noteTextEdit.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.noteTextEdit.setObjectName("noteTextEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.noteTextEdit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelButton = QtWidgets.QPushButton(parent=new_event_dialog)
        self.cancelButton.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.saveButton = QtWidgets.QPushButton(parent=new_event_dialog)
        self.saveButton.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(new_event_dialog)
        QtCore.QMetaObject.connectSlotsByName(new_event_dialog)

    def retranslateUi(self, new_event_dialog):
        _translate = QtCore.QCoreApplication.translate
        new_event_dialog.setWindowTitle(_translate("new_event_dialog", "New Event"))
        self.typeLabel.setText(_translate("new_event_dialog", "Type"))
        self.typeComboBox.setItemText(0, _translate("new_event_dialog", "Rejection"))
        self.typeComboBox.setItemText(1, _translate("new_event_dialog", "Interview"))
        self.typeComboBox.setItemText(2, _translate("new_event_dialog", "Test"))
        self.typeComboBox.setItemText(3, _translate("new_event_dialog", "Assignment"))
        self.typeComboBox.setItemText(4, _translate("new_event_dialog", "Offer"))
        self.dateLabel.setText(_translate("new_event_dialog", "Date"))
        self.dateDateEdit.setDisplayFormat(_translate("new_event_dialog", "dd/MM/yyyy"))
        self.noteLabel.setText(_translate("new_event_dialog", "Note"))
        self.cancelButton.setText(_translate("new_event_dialog", "Cancel"))
        self.saveButton.setText(_translate("new_event_dialog", "Add"))
